# Generated by Django 3.2 on 2024-05-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240523_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='step_id',
        ),
    ]
